Update patch set 2
Patch Set 2: Verified-1 Code-Review-2

05-04 04:39:13.315 25587 25587 E AndroidRuntime: FATAL EXCEPTION: main
05-04 04:39:13.315 25587 25587 E AndroidRuntime: Process: .dataservices, PID: 25587
05-04 04:39:13.315 25587 25587 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/qti/dpm/DpmService;
05-04 04:39:13.315 25587 25587 E AndroidRuntime:        at com.qti.dpmserviceapp.DpmServiceApp.onCreate(DpmServiceApp.java:42)
05-04 04:39:13.315 25587 25587 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4187)
05-04 04:39:13.315 25587 25587 E AndroidRuntime:        at android.app.ActivityThread.access$1500(ActivityThread.java:238)
05-04 04:39:13.315 25587 25587 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1933)
05-04 04:39:13.315 25587 25587 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-04 04:39:13.315 25587 25587 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
05-04 04:39:13.315 25587 25587 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7701)
05-04 04:39:13.315 25587 25587 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-04 04:39:13.315 25587 25587 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-04 04:39:13.315 25587 25587 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
05-04 04:39:13.315 25587 25587 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.qti.dpm.DpmService
05-04 04:39:13.315 25587 25587 E AndroidRuntime:        ... 10 more

Patch-set: 2
Reviewer: Gerrit User 1002322 <1002322@56841c99-7c94-43d4-bf0b-cb4707e66d55>
Label: Code-Review=-2
Label: Verified=-1